---
- name: run apt get and install unbound
  apt:
    name: unbound
    state: latest
    update_cache: yes

- name: Download root hints
  get_url:
    url: "{{ dns_root_hints_url }}"
    dest: /var/lib/unbound/root.hints
    mode: '0666'

- name: Create a directory if it does not exist
  file:
    path: /etc/unbound/unbound.conf.d/
    state: directory
    mode: '0755'

- name: copy pihole.conf template
  template:
    src: "{{ item }}.j2"
    dest: "/etc/unbound/unbound.conf.d/{{ item }}"
    group: "{{ dns_os_group }}"
    owner: "{{ dns_os_user }}"
  notify: restart unbound
  loop:
    - pi-hole.conf
    - local-network.conf

- name: delete old motd
  file:
    path: "/etc/motd"
    state: absent

- name: copy motd template
  template:
    src: "20-info.j2"
    dest: "/etc/update-motd.d/20-info"
    group: "root"
    owner: "root"
    mode: 0644

- name: copy root update scripte
  template:
    src: "{{ item.src }}.j2"
    dest: "/usr/local/bin/{{ item.src }}"
    group: "root"
    owner: "root"
    mode: "{{ item.mode }}"
  loop:
    - { src: autoupdatelocalroot , mode: 755 }
    - { src: updateunboundconf , mode: 744 }

- name: add script for rootupdate to crontab
  cron:
    name: autoupdatelocalroot
    weekday: "6"
    minute: "20"
    hour: "4"
    user: root
    job: "/usr/local/bin/autoupdatelocalroot"

# - name: run autoupdatelocalroot
#   shell: autoupdatelocalroot

  # TODO:
  #   - ntp?
  #   -
  # https://www.kuketz-blog.de/pi-hole-unbound-hyperlocal-keine-werbung-groesstmoegliche-unabhaengigkeit/