---
include:
  - project: knell-internal/templates
    file: Default-CI-Docker.gitlab-ci.yml

variables:
  RUN_ANSIBLE_LINT: "true"
  ANSIBLE_CONFIG: $CI_PROJECT_DIR/ansible.cfg
  CI_BASE_IMAGE: python
  CI_BASE_IMAGE_TAG: 3-bullseye
  KANIKO_BUILD_ARGS: --build-arg BASE_IMAGE=${CI_BASE_IMAGE} --build-arg BASE_IMAGE_TAG=${CI_BASE_IMAGE_TAG}
