# -*- mode: ruby -*-
# vi: set ft=ruby :

# Local virtual box based docker test environment.

# Requirements:
# - CPUs: 2+
# - MEM: 2GB+

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.disksize.size = '50GB'

  # give vm 2GB ram and 2 cores
  config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
  end

  # sync etc docker folder to virtual machine - this is for using client certificates for docker
  # registries
  config.vm.synced_folder "./", "/opt/ansible",
                             owner: "vagrant",
                             group: "users",
                             mount_options: ["dmode=775,fmode=774"] # "synced_folders/ansible"

  # install docker on vm startup (internet connection required)
  # for all options see here: https://www.vagrantup.com/docs/provisioning/docker.html
  #config.vm.provision "docker" do |docker|
    #docker.pull_images "YOUR_IMAGE"
  #end

  # if you want to use shell commands to do further setups uncomment the following:
  #config.vm.provision "shell", inline: <<-SHELL
  #  # put your inline shell commands here if needed
  #SHELL
  config.vm.provision "shell", path: "./scripts/initial_install.sh"
end
