---
- name: Block for become=true
  become: true
  block:
    - name: Ensure epel-release is installed
      ansible.builtin.dnf:
        name: "epel-release"
        state: present

    - name: Install os_os_prepare_packagespa
      ansible.builtin.dnf:
        name: "{{ os_prepare_packages }}"
        state: present

    - name: Create data dirs
      ansible.builtin.file:
        path: "{{ item.name }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "0770"
      loop:
        - name: "{{ storage_base_path }}"
          owner: root
          group: data
