---
- name: "({{ task_filename }}) block for become=true"
  become: true
  block:
    - name: "({{ task_filename }}) Create {{ app_name }} dirs"
      ansible.builtin.file:
        path: "{{ app_path }}/{{ item.name }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "0755"
      loop:
        - name: ""
          owner: root
          group: data
        - name: config
          owner: 1001
          group: 1001
        - name: semaphore_postgres
          owner: 999
          group: 999
