---
- name: "block for become=true"
  become: true
  block:
    - name: "Create {{ app_name }} dirs"
      ansible.builtin.file:
        path: "{{ app_path }}/{{ item.name }}"
        state: directory
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('data') }}"
        mode: "{{ item.mode | default('0755') }}"
      loop:
        - name: ""
