---
- name: Block for become=true
  become: true
  when: k3s_gitlab_runner_namespace_create
  run_once: true
  block:
    - name: Create K3s namespace
      kubernetes.core.k8s:
        name: "{{ k3s_gitlab_runner_namespace | lower }}"
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: "{{ k3s_gitlab_runner_kubeconfig_path }}"
        validate_certs: "{{ http.ssl_verify }}"
