---
- name: "Download Pi-Hole installer"
  get_url:
      url: https://install.pi-hole.net
      dest: ~/install-pihole.sh
      mode: 0740

- name: Create pihole configuration directory
  file:
    name: "{{ dns_pihole_config }}"
    state: directory
    owner: "{{ dns_os_user }}"
    group: "{{ dns_os_group }}"
    mode: 0755

- name: Create pihole configuration
  become: True
  template:
    src: "setupVars.conf.j2"
    dest: "{{ dns_pihole_config }}/setupVars.conf"
    owner: root
    group: root
    mode: 0644

- name: Check if pihole installed
  command: pihole -v >/dev/null 2>&1
  register: dns_pihole_installed
  ignore_errors: yes

- debug: msg="{{ dns_pihole_installed.rc }}" # it returns rc 1
- debug: var=dns_pihole_installed

- name: Install Pi-Hole
  shell: "~/install-pihole.sh --unattended"
  register: dbg_install_pihole
  #when: dns_pihole_installed == False

- name: Set PiHole to update every week
  become: True
  replace:
    path: /etc/cron.d/pihole
    regexp: '^#(.*updatePihole.*)$'
    replace: '\1'
    backup: yes

- name: Create pihole configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ dns_os_user }}"
    group: "{{ dns_os_group }}"
    mode: 0644
  loop:
    - { src: adlists.list.j2, dest: /etc/pihole/adlists.list }
    - { src: whitelist.txt.j2, dest: /etc/pihole/whitelist.txt }
  notify: restart pihole

- name: run pihole commands
  command: "{{ item }}"
  loop:
    - "pihole -a -p {{ dns_pihole_password }}"
    - pihole updateGravity