---
- name: Block for become=true
  block:
    - name: Create watchtower dirs
      ansible.builtin.file:
        path: "{{ watchtower_path }}/"
        state: directory
        mode: "0644"

  become: true
