---
all:
  hosts:
    dns.knell.dev:
      ansible_host: 10.0.0.2
      ansible_user: root
      ansible_pass: 6c3@sG**%LYRqdGQI2#S
      ansible_ssh_pass: "{{ ansible_pass }}"
      ansible_become_pass: "{{ ansible_pass }}"
    dns2.knell.dev:
      ansible_host: 10.0.0.91
      ansible_user: root
      ansible_pass: lol123
      ansible_ssh_pass: "{{ ansible_pass }}"
      ansible_become_pass: "{{ ansible_pass }}"
    gitlab.knell.dev:
      ansible_host: 10.0.0.10
      ansible_user: knell
      ansible_pass: lol123
      ansible_ssh_pass: "{{ ansible_pass }}"
      ansible_become_pass: "{{ ansible_pass }}"
      