###############################################################################
# Default Values for Role - Might contain placeholders for passwords - NOT live
###############################################################################
---
# Setting sof other roles
# Gitlab settings
con_gitlab_external_url: "http://example.com/" # noqa var-naming[no-role-prefix]
k3s_gitlab_runner_gitlab_external_url: "{{ con_gitlab_external_url }}"

# Kubernetes settings
k3s_gitlab_runner_namespace_create: true
k3s_gitlab_runner_namespace: "gitlab-runner"
k3s_gitlab_runner_kubeconfig_path: /etc/rancher/k3s/k3s.yaml

# Runner settings
# Needs to be get from UI
k3s_gitlab_runner_token: token
k3s_gitlab_runner_concurrent: 50

k3s_gitlab_runner_config_list:
  - |
    [[runners]]
      [runners.kubernetes]
        image = "python:3"
        pull_policy = "always"
        allowed_pull_policies = ["always", "if-not-present", "never"]
        # [runners.cache]
        #   Type = "s3"
        #   Shared = true
        #   [runners.cache.s3]
        #     ServerAddress = "172.17.152.121:9000"
        #     AccessKey = "S3gitlab"
        #     SecretKey = "S3gitlab"
        #     BucketName = "gitlab-runner-s3-cache"
        #     Insecure = true
