---
- name: User/group block
  block:
    - name: Create system group
      group:
        name: "{{ gitlab_runner_group }}"
        system: true
        state: present

    - name: Create system user
      user:
        name: "{{ gitlab_runner_user }}"
        shell: /sbin/nologin
        append: yes
        createhome: no
        comment: "Created by Ansible"
        group: "{{ gitlab_runner_group }}"
  when: os_create_user
  become: yes

- name: Create gitlab-runner paths
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ gitlab_runner_user }}"
    group: "{{ gitlab_runner_group }}"
    mode: "0755"
    recurse: yes
  loop:
    - "{{ gitlab_runner_base_path }}"
  become: yes
