---
- name: Download lastest gitlab runner
  get_url:
    url: "{{ gitlab_runner_download_url }}"
    dest: "{{ gitlab_runner_bin_path }}"
    mode: 0755

- name: Check for existing runner installation
  stat:
    path: /etc/systemd/system/gitlab-runner.service
  register: runner_result

- name: install gitlab runner
  shell: |
    gitlab-runner install --user={{ gitlab_runner_user }} --working-directory={{ gitlab_runner_base_path }}
  when: not runner_result.stat.exists

- name: start gitlab runner
  shell: |
    sudo gitlab-runner start
  when: not runner_result.stat.exists

- name: install gitlab runner
  shell: |
    gitlab-runner list
  register: runner_list

- name: include register loop
  block:
    - include_tasks: register.yml
      loop: "{{ gitlab_runner_list }}"
      loop_control:
        loop_var: runner_item
  become: yes

- name: restart all gitlab runners
  shell: |
    gitlab-runner restart
