---
- name: Grab current existing users
  uri:
    url: "{{ gitlab_url }}/api/v4/projects/"
    method: GET
    validate_certs: no
    status_code: 200
    body_format: json
    headers:
          Content-Type: application/json
          Authorization: "Bearer {{ gitlab_admin_access_token.json.access_token  }}"
  register: gitlab_existing_projects

- name: Concatenate a list to string
  set_fact:
    gitlab_project_id: "{{ gitlab_existing_projects.json | json_query(query) }}"
  vars:
    query: "[?name=='{{ runner_item.registration.name }}'].id | [0]"

- name: reset project token and grab token
  uri:
    url: "{{ gitlab_url }}/api/v4/projects/{{ gitlab_project_id }}/runners/reset_registration_token"
    method: POST
    validate_certs: no
    status_code: 200,201
    body_format: json
    headers:
        Content-Type: application/json
        Authorization: "Bearer {{ gitlab_admin_access_token.json.access_token }}"
  register: gitlab_project_token

- name: register project gitlab runner
  shell: |
    gitlab-runner register \
    --non-interactive \
    --url "{{ runner_item.url }}" \
    --name "{{ runner_item.runner_name }}" \
    --registration-token '{{ gitlab_project_token.json.token }}' \
    --executor "{{ runner_item.executor }}" \
    --docker-image "{{runner_item.docker_image | default("alpine:latest") }}" \
    --maintenance-note "Ansible installed runner" \
    --tag-list "{{ runner_item.tags }}" \
    --run-untagged="{{ runner_item.run_untagged }}" \
    --locked="{{ runner_item.locked }}" \
    --access-level="{{ runner_item.protected }}"
  register: project_result
  retries: 10
  delay: 5
  until: project_result.rc == 0
