---
- name: "({{ task_filename }}) block for become=true"
  become: true
  block:
    - name: "({{ task_filename }}) Template {{ app_name }} files"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '{{ item.mode | default("0644") }}'
      loop:
        - src: quadlet-gitlab.container.j2
          dest: "/etc/containers/systemd/gitlab.container"
        - src: "{{ con_gitlab_config_template }}"
          dest: "{{ app_path }}/config/gitlab.rb"
        - src: post-reconfigure.sh.j2
          dest: "{{ app_path }}/config/post-reconfigure.sh"
          mode: "0755"

    - name: "({{ task_filename }}) Template {{ app_name }} network"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '{{ item.mode | default("0644") }}'
      loop:
        - src: quadlet-gitlab_default.network.j2
          dest: /etc/containers/systemd/{{ con_gitlab_container_network_name }}.network
      when: con_gitlab_container_network_create

    - name: "({{ task_filename }}) Create a symbolic links for container services"
      ansible.builtin.file:
        src: "/etc/containers/systemd/{{ item }}"
        dest: "{{ app_path }}/quadlet-{{ item }}"
        state: link
      loop:
        - "gitlab.container"
        - "gitlab_default.network"

    - name: "({{ task_filename }}) start {{ app_name }} quadlet"
      ansible.builtin.systemd_service:
        state: "{{ con_gitlab_systemd_service_state }}"
        daemon_reload: true
        name: gitlab

    - name: "({{ task_filename }}) Ensure Application is started and accepting connections"
      ansible.builtin.uri:
        url: "{{ con_gitlab_external_url }}"
        return_content: true
        status_code: 200, 403
        follow_redirects: all
        timeout: 5
        validate_certs: "{{ http.ssl_verify }}"
      register: healthcheck
      until: healthcheck.status is defined and (healthcheck.status == 200 or healthcheck.status == 403)
      retries: "{{ http.retries }}"
      delay: "{{ http.delay }}"
