---
# LDAP
con_semaphore_ldap_enabled: false
con_semaphore_ldap_host: domain.local
con_semaphore_ldap_port: 389
con_semaphore_ldap_tls: "no"
con_semaphore_ldap_bind_dn: ""
con_semaphore_ldap_password: ""
con_semaphore_ldap_dn_search: ""
con_semaphore_ldap_mapping_uid: ""
con_semaphore_ldap_search_filter: ""

# OIDC
con_semaphore_oidc_enabled: false
con_semaphore_oidc_display_name: Sign in with Authentik
con_semaphore_oidc_display_provider_url: https://auth.example.com/application/o/ansible/
con_semaphore_oidc_display_client_id: id
con_semaphore_oidc_display_client_secret: secret
con_semaphore_oidc_display_redirect_url: "{{ con_semaphore_url }}/api/auth/oidc/authentik/redirect/"
