---
- name: "Playbook: ping"
  hosts: "{{ hosts_limit | default('all') }}"
  tasks:
    - name: Ping host for tests
      ansible.builtin.ping:
        data: pong

    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
